### ISSUE TITLE
[Purpur] Exception in thread "MultiLib data save"

### ISSUE THREAD

**Issue by Euphillya** [PureGero/MultiLib#2]
Reproduction of the error: Launch a plugin with MultiLib under Purpur (Test on Purpur) and switch off the server.

```md
[06:21:49 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'vp_the_end'
[06:21:49 INFO]: [ChunkHolderManager] Halted chunk system for world 'vp_the_end'
[06:21:49 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'vp_the_end'
[06:21:49 INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'vp_the_end' in 0.00s
[06:21:49 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[06:21:49 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[06:21:49 INFO]: Flushing Chunk IO
[06:21:49 INFO]: Closing Thread Pool
[06:21:49 INFO]: Closing Server
[06:21:49 WARN]: Exception in thread "MultiLib data save" java.lang.NoClassDefFoundError: com/github/puregero/multilib/bukkit/StoredData
[06:21:49 WARN]:        at SkyblockVP-2.1-all.jar//com.github.puregero.multilib.bukkit.BukkitImpl$1.run(BukkitImpl.java:31)
[06:21:49 WARN]: Caused by: java.lang.ClassNotFoundException: com.github.puregero.multilib.bukkit.StoredData
[06:21:49 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179)
[06:21:49 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126)
[06:21:49 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[06:21:49 WARN]:        ... 1 more
```

**Comment by PureGero** [comment]
Fixed in version 1.1.9
