### ISSUE TITLE
Exception when closing server

### ISSUE THREAD

**Issue by alec-jensen** [PureGero/MultiLib#5]
I get this exception when I stop the server: (paper 1.20 build 10)
```
[14:53:36 WARN]: Exception in thread "MultiLib data save" java.lang.BootstrapMethodError: java.lang.IllegalStateException: zip file closed
[14:53:36 WARN]:        at Grumm-2.3.41.jar//me.alecjensen.grumm.shaded.com.github.puregero.multilib.bukkit.BukkitImpl$1.run(BukkitImpl.java:31)
[14:53:36 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[14:53:36 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[14:53:36 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[14:53:36 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[14:53:36 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[14:53:36 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195)
[14:53:36 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[14:53:36 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[14:53:36 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[14:53:36 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[14:53:36 WARN]:        ... 1 more
```

**Comment by PureGero** [comment]
This appears to have been fixed since version 1.1.9. Are you running the latest version?
